version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Pre-build phase started
      - aws --version
  build:
    commands:
      - echo Build started on `date`
      - chmod +x mvnw
      - ./mvnw clean package -DskipTests
  post_build:
    commands:
      - echo Build completed on `date`
      - mv target/*.jar application.jar
      - echo Creating deployment package
      - zip -r deploy.zip application.jar Procfile .ebextensions/* .platform/*

artifacts:
  files:
    - deploy.zip
    - .ebextensions/**/*
    - .platform/**/*
  discard-paths: no 